export const GET_TICKET_DETAIL = "GET_TICKET_DETAIL";
export const SEAT_BOOKING = "SEAT_BOOKING";
export const COMPLETE_BOOKING = "COMPLETE_BOOKING";
export const CHANGE_TAB_ACTIVE = "CHANGE_TAB_ACTIVE";
export const CHANGE_TAB = "CHANGE_TAB";
