export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_BANNER_LIST = "GET_BANNER_LIST";
export const GET_MOVIE_SHOWING = "GET_MOVIE_SHOWING";
export const GET_MOVIE_COMING = "GET_MOVIE_COMING";
export const GET_MOVIE_DEFAULT = "GET_MOVIE_DEFAULT";
